version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    ports: 
      - "8080:80"
    depends_on:
      - node
    networks:
      - default-network
  
  node:
    build:
      context: ./node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh index.js
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - default-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    networks:
      - default-network
    volumes:
      - ./mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

networks:
  default-network:
    driver: bridge